FROM mcr.microsoft.com/dotnet/sdk:9.0.203-noble-amd64
RUN pwsh -NonInteractive -Command Install-Module -Force -Scope AllUsers powershell-yaml
RUN apt-get update
RUN apt-get upgrade
RUN apt-get -y install curl
ENV VERSION="1.2.3"
RUN curl -LO "https://github.com/oras-project/oras/releases/download/v${VERSION}/oras_${VERSION}_linux_amd64.tar.gz" 
RUN ls
RUN mkdir -p oras-install/
RUN tar -zxf oras_${VERSION}_*.tar.gz -C oras-install/
RUN mv oras-install/oras /usr/local/bin/
RUN rm -rf oras_${VERSION}_*.tar.gz oras-install/
# Create a user group 'noroot'
RUN groupadd noroot
# Add a user noroot to group 'noroot'
RUN useradd --create-home --shell /bin/bash -u 1001 -g noroot noroot
COPY ./Installer.ps1 /script/Installer.ps1
RUN chown -R noroot /script
COPY ./get-custom-scripts /get-custom-scripts
RUN chown -R noroot /get-custom-scripts
RUN oras --help